---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        imagePullPolicy: Always
        args:
        - --web.enable-otlp-receiver
        - --config.file=/etc/prometheus/prometheus.yml
        ports:
        - name: http
          containerPort: 9090
        envFrom:
        - configMapRef:
            name: prometheus-env
      terminationGracePeriodSeconds: 180